baseURL = "http://example.com/"
languageCode = "en-us"
title = "WeSellChem"

theme = "hugo-arcana"

[params]
  description = "Your description here"
  home = "/"

[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "Home"
  url = "/"
  weight= "1"

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/pages/about/"

[[menu.main]]
  identifier = "Products"
  name = "Products"
  title = "Products"
  url = "/pages/products/"

[[menu.main]]
  identifier = "Customers"
  name = "Customers"
  title = "Customers"
  url = "/pages/customers/"
